"""
Данные карт персонажей и поддержки
Основано на "Магическая битва" (Jujutsu Kaisen)
"""

from utils.character_content import get_character_card_metadata

# Список доступных карт персонажей
CHARACTER_CARDS = [
    {
        "name": 'Годжо Сатору',
        "description": 'Сильнейший маг. Владелец Безграничной и Шести Глаз.',
        "rarity": 'legendary',
        "base_attack": 75,
        "base_defense": 60,
        "base_speed": 95,
        "base_hp": 320,
        "growth_multiplier": 1.15
    },
    {
        "name": 'Инумаки Тогэ',
        "description": 'Наследник Каминого. Речевая магия.',
        "rarity": 'rare',
        "base_attack": 42,
        "base_defense": 38,
        "base_speed": 60,
        "base_hp": 205,
        "growth_multiplier": 1.08
    },
    {
        "name": 'Итадори Юдзи',
        "description": 'Сосуд Сукуны. Обладает невероятной физической силой.',
        "rarity": 'epic',
        "base_attack": 58,
        "base_defense": 50,
        "base_speed": 70,
        "base_hp": 285,
        "growth_multiplier": 1.12
    },
    {
        "name": 'Рёмен Сукуна',
        "description": 'Король проклятий. Хозяин «Храма Злобы» и техник рассечения.',
        "rarity": 'legendary',
        "base_attack": 75,
        "base_defense": 60,
        "base_speed": 90,
        "base_hp": 330,
        "growth_multiplier": 1.15
    },
    {
        "name": 'Камо Норитоши',
        "description": 'Наследник Кровавой магии.',
        "rarity": 'common',
        "base_attack": 32,
        "base_defense": 28,
        "base_speed": 40,
        "base_hp": 175,
        "growth_multiplier": 1.05
    },
    {
        "name": 'Маки Дзэнин',
        "description": 'Мастер оружия. Нулевая целостность.',
        "rarity": 'epic',
        "base_attack": 56,
        "base_defense": 46,
        "base_speed": 78,
        "base_hp": 245,
        "growth_multiplier": 1.1
    },
    {
        "name": 'Мива Касуми',
        "description": 'Маг-новичок с мечом.',
        "rarity": 'common',
        "base_attack": 30,
        "base_defense": 26,
        "base_speed": 45,
        "base_hp": 165,
        "growth_multiplier": 1.05
    },
    {
        "name": 'Мута Кокичи',
        "description": 'Мехамару в кукле.',
        "rarity": 'common',
        "base_attack": 27,
        "base_defense": 30,
        "base_speed": 50,
        "base_hp": 160,
        "growth_multiplier": 1.04
    },
    {
        "name": 'Нанами Кенто',
        "description": 'Бывший офисный работник. Мастер пропорции.',
        "rarity": 'rare',
        "base_attack": 47,
        "base_defense": 44,
        "base_speed": 55,
        "base_hp": 215,
        "growth_multiplier": 1.09
    },
    {
        "name": 'Панда',
        "description": 'Абнормальный труп. Три ядра.',
        "rarity": 'rare',
        "base_attack": 45,
        "base_defense": 50,
        "base_speed": 50,
        "base_hp": 250,
        "growth_multiplier": 1.08
    },
    {
        "name": 'Фушигуро Мегуми',
        "description": 'Владелец Десяти Теней. Такумадау.',
        "rarity": 'epic',
        "base_attack": 54,
        "base_defense": 46,
        "base_speed": 75,
        "base_hp": 255,
        "growth_multiplier": 1.11
    },
    {
        "name": 'Тоджи Фушигуро',
        "description": 'Проклятие небес. Нулевая проклятая энергия, невероятная сила и скорость.',
        "rarity": 'legendary',
        "base_attack": 70,
        "base_defense": 54,
        "base_speed": 98,
        "base_hp": 305,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.14
    },
    {
        "name": 'Хакари Киндзи',
        "description": 'Игрок удачи. Его территория запускает «джекпот».',
        "rarity": 'epic',
        "base_attack": 60,
        "base_defense": 48,
        "base_speed": 72,
        "base_hp": 280,
        "growth_multiplier": 1.12
    },
    {
        "name": 'Хигурума',
        "description": 'Судья',
        "rarity": 'legendary',
        "base_attack": 58,
        "base_defense": 48,
        "base_speed": 70,
        "base_hp": 295,
        "growth_multiplier": 1.15
    },
            {
        "name": "Баттлердан",
        "description": "Мастер дебатов, вооружён клиньями и ключом.",
        "rarity": "mythical",
        "base_attack": 68,
        "base_defense": 56,
        "base_speed": 84,
        "base_hp": 310,
        "growth_multiplier": 1.14
    },
    {
        "name": "Годжослав",
        "description": "Ученик класса Годжо, изобретатель бесконечных белых.",
        "rarity": "mythical",
        "base_attack": 70,
        "base_defense": 60,
        "base_speed": 88,
        "base_hp": 315,
        "growth_multiplier": 1.14
    },
    {
        "name": "Оккоцу Юта",
        "description": "Особый класс. Носитель чудовищной проклятой энергии и связи с Рикой.",
        "rarity": "legendary",
        "base_attack": 72,
        "base_defense": 58,
        "base_speed": 82,
        "base_hp": 325,
        "base_ce": 135,
        "ce_regen": 12,
        "growth_multiplier": 1.15
    },
    {
        "name": "Кугисаки Нобара",
        "description": "Мастер техники гвоздей и соломенных кукол.",
        "rarity": "epic",
        "base_attack": 55,
        "base_defense": 42,
        "base_speed": 68,
        "base_hp": 240,
        "growth_multiplier": 1.1
    },
    {
        "name": "Тодо Аой",
        "description": "Грозный боец ближнего боя с безумной физической мощью.",
        "rarity": "epic",
        "base_attack": 64,
        "base_defense": 54,
        "base_speed": 66,
        "base_hp": 295,
        "growth_multiplier": 1.11
    },
    {
        "name": "Мэй Мэй",
        "description": "Наёмная магичка, предпочитающая точные и смертельные удары.",
        "rarity": "rare",
        "base_attack": 49,
        "base_defense": 40,
        "base_speed": 62,
        "base_hp": 220,
        "growth_multiplier": 1.08
    },
    {
        "name": "Чосо",
        "description": "Старший из братьев-проклятий. Управляет кровью с пугающей точностью.",
        "rarity": "legendary",
        "base_attack": 69,
        "base_defense": 52,
        "base_speed": 74,
        "base_hp": 305,
        "base_ce": 120,
        "ce_regen": 11,
        "growth_multiplier": 1.14
    },
    {
        "name": "Цукумо Юки",
        "description": "Особый класс. Ломает бой одной чудовищной массой и ударной силой.",
        "rarity": "legendary",
        "base_attack": 74,
        "base_defense": 57,
        "base_speed": 77,
        "base_hp": 320,
        "base_ce": 125,
        "ce_regen": 12,
        "growth_multiplier": 1.15
    },
    {
        "name": "Гэто Сугуру",
        "description": "Мастер манипуляции проклятиями, собирающий армию духов.",
        "rarity": "legendary",
        "base_attack": 71,
        "base_defense": 56,
        "base_speed": 73,
        "base_hp": 315,
        "base_ce": 130,
        "ce_regen": 12,
        "growth_multiplier": 1.14
    },
    {
        "name": "Наоя Дзэнин",
        "description": "Высокомерный и невероятно быстрый наследник клана Дзэнин.",
        "rarity": "epic",
        "base_attack": 61,
        "base_defense": 45,
        "base_speed": 92,
        "base_hp": 250,
        "growth_multiplier": 1.11
    },
    {
        "name": "Ацуя Кусакабе",
        "description": "Наставник школы новой тени. Мастер простой территории и мгновенного батто.",
        "rarity": "epic",
        "base_attack": 59,
        "base_defense": 55,
        "base_speed": 74,
        "base_hp": 285,
        "base_ce": 110,
        "ce_regen": 11,
        "growth_multiplier": 1.11
    },
    {
        "name": "Такума Ино",
        "description": "Маг, полагающийся на маску и технику благовестных зверей в ближнем бою.",
        "rarity": "rare",
        "base_attack": 51,
        "base_defense": 44,
        "base_speed": 67,
        "base_hp": 245,
        "base_ce": 105,
        "ce_regen": 10,
        "growth_multiplier": 1.09
    },
    {
        "name": "Наобито Дзэнин",
        "description": "Бывший глава клана Дзэнин. Его проекционная магия превращает скорость в оружие.",
        "rarity": "legendary",
        "base_attack": 68,
        "base_defense": 52,
        "base_speed": 96,
        "base_hp": 290,
        "base_ce": 120,
        "ce_regen": 11,
        "growth_multiplier": 1.14
    },
    {
        "name": "Дагон",
        "description": "Проклятие особого уровня. Управляет океаном в своей территории.",
        "rarity": "legendary",
        "base_attack": 66,
        "base_defense": 58,
        "base_speed": 52,
        "base_hp": 310,
        "base_ce": 120,
        "ce_regen": 11,
        "growth_multiplier": 1.14,
        "innate_technique": "Океаническая катастрофа",
        "abilities": ["Приливный обвал", "Стая глубин"],
        "domain_name": "Горизонт плена скандхи",
    },
    {
        "name": "Ханами",
        "description": "Проклятие природы. Огромная защита и контроль поля.",
        "rarity": "legendary",
        "base_attack": 60,
        "base_defense": 70,
        "base_speed": 45,
        "base_hp": 340,
        "base_ce": 125,
        "ce_regen": 12,
        "growth_multiplier": 1.14,
        "innate_technique": "Проклятая флора",
        "abilities": ["Корни-ловушки", "Цветочный обвал"],
        "domain_name": "Цветущий гнев",
    },
    {
        "name": "Дзёго",
        "description": "Проклятие вулкана. Огромный урон по области.",
        "rarity": "legendary",
        "base_attack": 74,
        "base_defense": 50,
        "base_speed": 65,
        "base_hp": 300,
        "base_ce": 130,
        "ce_regen": 12,
        "growth_multiplier": 1.14,
        "innate_technique": "Огненная катастрофа",
        "abilities": ["Вулканический залп", "Извержение"],
        "domain_name": "Пылающий кратер",
    },
    {
        "name": "Ураумэ",
        "description": "Слуга Сукуны. Управляет льдом с высокой точностью.",
        "rarity": "epic",
        "base_attack": 62,
        "base_defense": 46,
        "base_speed": 80,
        "base_hp": 255,
        "base_ce": 115,
        "ce_regen": 11,
        "growth_multiplier": 1.12,
        "innate_technique": "Ледяная техника",
        "abilities": ["Морозное копьё", "Ледопад"],
        "domain_name": "Ледяная камера",
    },
    {
        "name": "Кашимо Хадзимэ",
        "description": "Древний маг. Электрические атаки с гарантированным уроном.",
        "rarity": "legendary",
        "base_attack": 76,
        "base_defense": 48,
        "base_speed": 92,
        "base_hp": 295,
        "base_ce": 120,
        "ce_regen": 11,
        "growth_multiplier": 1.15,
        "innate_technique": "Проклятое электричество",
        "abilities": ["Громовой разряд", "Мифический зверь: Янтарь"],
        "domain_name": "Поле грома",
    },
    {
        "name": "Махито",
        "description": "Проклятие человеческой ненависти. Искажает души и форму тела.",
        "rarity": "legendary",
        "base_attack": 72,
        "base_defense": 54,
        "base_speed": 84,
        "base_hp": 305,
        "base_ce": 128,
        "ce_regen": 12,
        "growth_multiplier": 1.15,
        "innate_technique": "Преобразование души",
        "abilities": ["Касание души", "Искажённый обвал"],
        "domain_name": "Мгновенное воплощение совершенства",
    },
    {
        "name": "Кендзяку",
        "description": "Древний манипулятор, управляющий проклятиями и чужими техниками.",
        "rarity": "legendary",
        "base_attack": 73,
        "base_defense": 60,
        "base_speed": 78,
        "base_hp": 320,
        "base_ce": 135,
        "ce_regen": 12,
        "growth_multiplier": 1.15,
        "innate_technique": "Манипуляция проклятиями",
        "abilities": ["Гравитационный обвал", "Узумаки"],
        "domain_name": "Чрево поглощённых проклятий",
    },
  ]

for card in CHARACTER_CARDS:
    metadata = get_character_card_metadata(card.get("name"))
    if metadata:
        card.update(metadata)

# Карты шикигами (поддержка)
SHIKIGAMI_CARDS = [
    {
        "name": "Великая Змея",
        "description": "Шикигами Фушигуро. Мощная змея.",
        "rarity": "epic",
        "base_attack": 36,
        "base_defense": 40,
        "base_speed": 45,
        "base_hp": 150,
        "growth_multiplier": 1.09,
    },
    {
        "name": "Колесница Серебряного Льва",
        "description": "Стремительный шикигами с сильной защитой.",
        "rarity": "epic",
        "base_attack": 33,
        "base_defense": 44,
        "base_speed": 70,
        "base_hp": 145,
        "growth_multiplier": 1.09,
    },
    {
        "name": "Кукла Мехамару",
        "description": "Мехамару в кукле. Надёжная поддержка.",
        "rarity": "common",
        "base_attack": 22,
        "base_defense": 18,
        "base_speed": 40,
        "base_hp": 95,
        "growth_multiplier": 1.05,
    },
    {
        "name": "Кукла Панды",
        "description": "Кукольное тело с хорошим балансом характеристик.",
        "rarity": "rare",
        "base_attack": 33,
        "base_defense": 36,
        "base_speed": 40,
        "base_hp": 125,
        "growth_multiplier": 1.07,
    },
    {
        "name": "Махорага",
        "description": "Божественный шикигами. Адаптируется к атакам.",
        "rarity": "legendary",
        "base_attack": 50,
        "base_defense": 44,
        "base_speed": 50,
        "base_hp": 185,
        "growth_multiplier": 1.12,
    },
    {
        "name": "Нуэ",
        "description": "Летающий шикигами с высокой скоростью.",
        "rarity": "epic",
        "base_attack": 39,
        "base_defense": 28,
        "base_speed": 65,
        "base_hp": 130,
        "growth_multiplier": 1.1,
    },
    {
        "name": "Пес",
        "description": "Быстрый шикигами ближнего боя.",
        "rarity": "rare",
        "base_attack": 28,
        "base_defense": 24,
        "base_speed": 55,
        "base_hp": 115,
        "growth_multiplier": 1.07,
    },
    {
        "name": "Божественный Пёс (Белый)",
        "description": "Быстрый и точный атакующий шикигами.",
        "rarity": "rare",
        "base_attack": 32,
        "base_defense": 26,
        "base_speed": 60,
        "base_hp": 120,
        "growth_multiplier": 1.07,
    },
    {
        "name": "Божественный Пёс (Чёрный)",
        "description": "Усиленная версия с повышенным уроном.",
        "rarity": "epic",
        "base_attack": 40,
        "base_defense": 30,
        "base_speed": 62,
        "base_hp": 135,
        "growth_multiplier": 1.09,
    },
    {
        "name": "Тотем Олень",
        "description": "Лечащий шикигами.",
        "rarity": "epic",
        "base_attack": 20,
        "base_defense": 40,
        "base_speed": 50,
        "base_hp": 170,
        "growth_multiplier": 1.1,
    },
    {
        "name": "Тигр Погибели",
        "description": "Агрессивный шикигами с высоким уроном.",
        "rarity": "epic",
        "base_attack": 44,
        "base_defense": 28,
        "base_speed": 58,
        "base_hp": 140,
        "growth_multiplier": 1.1,
    },
]

# Оружие (проклятые предметы, слот оружия)
WEAPON_CARDS = [
    {
        "name": "Игривое облако",
        "description": "Проклятое оружие. Увеличивает урон обычных атак.",
        "rarity": "epic",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Клинок ясности души",
        "description": "Проклятый клинок. Игнорирует защиту цели.",
        "rarity": "legendary",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Перевернутое небесное копье",
        "description": "Пробивает Бесконечность только обычными ударами.",
        "rarity": "legendary",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Цепь тысячи миль",
        "description": "Может атаковать на дистанции, игнорируя уклонение.",
        "rarity": "epic",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Чёрный клинок",
        "description": "Увеличивает шанс чёрной вспышки.",
        "rarity": "legendary",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Проклятые перчатки",
        "description": "Увеличивают физический урон.",
        "rarity": "rare",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
]

# Пакты (пакт-слот)
PACT_CARDS = [
    {
        "name": "Пакт силы",
        "description": "Следующая атака +50%, CE реген -40%.",
        "rarity": "rare",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Пакт усердия",
        "description": "После боя даёт +50% опыта, затем исчезает.",
        "rarity": "rare",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Пакт прорыва",
        "description": "После боя даёт +100% опыта, затем исчезает.",
        "rarity": "epic",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Пакт просветления",
        "description": "После боя даёт +150% опыта, затем исчезает.",
        "rarity": "legendary",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
    {
        "name": "Пакт выживания",
        "description": "При смертельном уроне остаётся 1 HP (1 раз).",
        "rarity": "legendary",
        "base_attack": 0,
        "base_defense": 0,
        "base_speed": 0,
        "base_hp": 0,
        "base_ce": 0,
        "ce_regen": 0,
        "growth_multiplier": 1.0,
    },
]


ALL_CARDS = CHARACTER_CARDS + SHIKIGAMI_CARDS + WEAPON_CARDS + PACT_CARDS

# Шансы редкости по умолчанию
RARITY_CHANCES = {'common': 70, 'rare': 30, 'epic': 10, 'legendary': 3, 'mythical': 0}


def get_cards_by_rarity(rarity: str):
    """Получить все карты заданной редкости"""
    return [card for card in ALL_CARDS if card["rarity"] == rarity]


def get_character_cards():
    """Получить список карт персонажей"""
    return CHARACTER_CARDS


def get_support_cards():
    """Получить список карт поддержки"""
    return SHIKIGAMI_CARDS + WEAPON_CARDS
